config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :patients
  resources :groups

  get '/my-patients', to: 'users#patient'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"
  devise_scope :user do
    get 'users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :patients
  has_one_attached :thumbnail
  validate :acceptable_image

  private
  def acceptable_image
    return unless thumbnail.attached?
    unless thumbnail.byte_size <= 300.kilobyte
      errors.add(:thumbnail, "file too big")
    end
  end

  end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :patient_creator, class_name: 'User'
  belongs_to :group, optional: true

  scope :without_group, ->(patient_creator_id) {where('group_id IS NULL AND patient_creator_id = ?', patient_creator_id).order(created_at: :desc)}
  # the patient_creator_id is a argument which must be passed in the controller
  scope :with_group, ->(patient_creator_id) {where('group_id IS NOT NULL AND patient_creator_id = ?', patient_creator_id).order(created_at: :desc)}
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         validates :email, presence: true, uniqueness: true
         validates :password, presence: true, length: { in: 5..10 }
has_many :groups
has_many :patients, foreign_key: 'patient_creator_id', class_name: 'Patient'
       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.new(groups_params)
    if @group.save
      redirect_to my_groups_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @group = Group.find(params[:id])
  end

  private

  def groups_params
    params.require(:group).permit(:name, :icon, :thumbnail)
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :authenticate_user!
  def index
    @patients_without_group = Patient.without_group(current_user.id)
    @sum_of_amount = @patients_without_group.sum('amount')
  end

  def new
    @patient = Patient.new
    
    # 3.times {@patient.build_patients_group}
    
  end

  def create
    @patient = Patient.new(patient_params)
    @patient.patient_creator_id= current_user.id
    if @patient.save && @patient.group.present?
      flash[:notice] = "Patient #{@patient.name} created "
      redirect_to my_patients_path
    elsif @patient.save && @patient.group.nil?
      flash[:notice] = "Patient #{@patient.name} created without a group"
      redirect_to patients_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def patient_params
    params.require(:patient).permit( :name, :amount,:group_id)
  end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => e
      if get?
        raise e
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @patients = Patient.all
    @groups = Group.all
  end

  def show

  end

  def patient
    @patients_with_group = Patient.with_group(current_user.id)
    @sum_of_amount = @patients_with_group.sum('amount')
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/groups/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-danger ps-5 d-flex bg-dark">
  <%= link_to 'Clinical Tech', 
  root_path, class:"navbar-brand fw-bold fs-4 logo text-white fw-bold w-50 mx-auto"%>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button> <div class="  flex-grow-1 pe-5 d-flex justify-content-end" id="navbarNav">
  <div>

  
    <ul class="navbar-nav  d-flex flex-row gap-3">
      <li class="nav-item active">
  
      <% if user_signed_in? %>
      <%# <li class="nav-item"> %>
        <%# <%= link_to 'Write an Article ',  new_article_path, class:"nav-link logo text-white"%> 
      <%# </li> %>
      <li class="nav-item">
        <%= link_to 'Edit Profile ',  edit_user_registration_path, class:"nav-link logo text-white"%> 
      </li>
      <li class="nav-item">
        <%= link_to "Sign out", destroy_user_session_path, method: :delete, class:"nav-link logo text-white" %>
      </li>
      <% else %>
      <%# <li class="nav-item"> %>
        <%# <%= link_to 'Write an Article',  new_article_path, class:"nav-link logo text-white"%>
      <%# </li> %>
      <li>
          <%= link_to 'Sign up', new_user_registration_path, class:"nav-link logo text-white"%>
      </li>
      <li class="nav-item">
        <%= link_to 'Sign in', new_user_session_path, class:"nav-link logo text-white"%>
      </li></div>
      <% end %>
  </div>
</nav>

app/views/groups/index.html.erb
<h2 class = "d-flex justify-content-center align-items-center m-4 fw-bold">

<div class = "d-flex ml-4 justify-content-center align-items-center">


Patients Groups
</h2><div class = "m-4 d-flex ml-4 justify-content-around align-items-center" >
<% if @groups%>

<p>
<% @groups.each do |group|%>
<div>

<%=link_to(group.name, group, class:"fw-bold text-decoration-none text-secondary fs-3")%>

<div>
<%= image_tag group.thumbnail, class:"img_res" if group.thumbnail.present? %>
</div>
</div>

<div>

<%= group.icon%>
</div>

<%end%>
</p>

<% else%>

<p> You have not added any group</p>
</div>

<%end%>


</div>

<div class = "d-flex ml-4 flex-column justify-content-around align-items-center">
<p><%= link_to('Add new group', new_group_path,class:"fw-bold text-decoration-none text-secondary"	)%> </p>
<p> <%= link_to("Back", :back, class:"fw-bold text-decoration-none text-secondary")%> </p>

</div>

app/views/groups/new.html.erb
<div class = "container-fluid d-flex justify-content-center align-items-center"> <%= form_with(model: @group, local: true, multipart: true) do |form|%> <div>
<div>
<%= form.label :name, class:"form-label fw-bold"%> <br>
<%= form.text_field :name, size:"48", class:"form-control"%>
</div>
      

<div>

<%= form.label :icon, class:"form-label fw-bold"%> <br>
<%= form.text_field :amount, size:"48", class:"form-control"%>
</div>

<div><%= form.label :thumbnail,   "Project Icon", class:"form-label fw-bold" %> <br>
<%= form.file_field :thumbnail %>
      
</div> 

<div> <%= form.submit%> </div>

<%end%></div>

app/views/groups/show.html.erb
<h2 class = "d-flex justify-content-center align-items-center m-4 fw-bold">

The <%= @group.name%> patient transactions
</h2>

<section>


<table class = "table table-hover table-responsive caption-top bg-light vw-100">
<caption> <strong> List of patients</strong> </caption>
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      
      <th scope="col">Treatment Cost</th>
    </tr>
  </thead>
  <%index = 0%>
  <% @group.patients.each do |gr|%>
<tbody>
    <tr>
      <th scope="row"><%= index = index + 1 %></th>
      <td > <%= gr.name %> </p></td>
      
      
      <td> &#8358 <%= gr.amount %></td>
      
    </tr>
<%end%>
<td class = "fw-bold">Total treatment cost </td> <td></td>  <td class = "fw-bold"> &#8358 <%=  @sum_of_amount%>
</td>
    </tbody>
</table>


</section>
<p> <%= link_to("Back", :back)%> </p>

app/views/layouts/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <% notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClinicalTech</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed&display=swap" rel="stylesheet">
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    
    <%= stylesheet_link_tag "custom", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class = "roboto">

<%= render 'groups/header' %>
 <div class= "fs-4 fw-normal d-flex justify-content-center align-items-center text-success" >
 <%= flash[:alert]%>
  <%= flash[:notice]%>
 </div> 
    <%= yield %>
  </body>
</html>

app/views/patients/_form.html.erb
<p class = "container-fluid d-flex justify-content-center mt-4 fs-3 fw-bold text-black-50">Patient Information</p>
<div>

<div class = "container-fluid d-flex justify-content-center"> <%= form_for @patient do |form|%>

<p class = "fs-3 fw-bold"> Create Patient  </p > 

<form class="form-control"> 
 <div>
<%= form.label :name, class:"form-label fw-bold"%> <br>
<%= form.text_field :name, size:"48", class:"form-control"%>

      
</div> 
<div class = "mt-2" >

<%= form.label "Treatment cost", class:"form-label fw-bold" %> <br>
<%= form.text_field :amount, size:"48", class:"form-control "%>
      
</div> 

<div><%= form.label "Select patient group:", class: "mt-2 fw-bold " %>

<%# <%= select('patients', 'groups_id', Group.all.collect {|g| [g.name, g.id]}, {include_blank: true}) %> 


</div>
<%= form.collection_select(:group_id, Group.all, :id, :name, {include_blank: true} ,{class:"form-select"}) %>
  <br />

<span> <%= form.submit class:"btn btn-success" %> <%= link_to("Back", :back, class: "me-3 btn btn-danger") %> </span>
</form> 
<%end%></div>





</div>

app/views/patients/index.html.erb
<h2 class = "d-flex justify-content-center">Patients without group</h2>

<ul> <% if @patients_without_group.any? %> 


<table class = "table table-hover table-responsive caption-top bg-light vw-100">
<caption> <strong> List of patients</strong> </caption>
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      
      <th scope="col">Treatment Cost</th>
    </tr>
  </thead>
  <%index = 0%>
  <% @patients_without_group.each do |patient|%>
<tbody>
    <tr>
      <th scope="row"><%= index = index + 1 %></th>
      <td > <%= patient.name %> </p></td>
      
      
      <td> &#8358 <%= patient.amount %></td>
      
    </tr>
<%end%>
<td class = "fw-bold">Total treatment cost </td> <td></td>  <td class = "fw-bold"> &#8358 <%=  @sum_of_amount%>
</td>
    </tbody>
</table>
<% else %>
<p> No patient without group</p>

<% end%>

<p> <%= link_to("Back", :back, class:"fw-bold text-decoration-none text-secondary")%> </p>
<div class = "d-flex justify-content-between mt-4"> <p><%= link_to('Add new patient', new_patient_url, class:"fw-bold text-decoration-none text-secondary")%> </p>

app/views/patients/new.html.erb
<%= render "form", patient: @patient %>

app/views/users/group.html.erb
<div>
<% if @groups%>

<p>
<% @groups.each do |group|%>
<div>

<%= group.name%>

</div>

<div>

<%= group.icon%>
</div>

<div>
<%= image_tag group.thumbnail, class:"img_res" if group.thumbnail.present? %>
</div>
<%end%>
</p>

<% else%>

<p> You have not added any group</p>
</div>

<%end%>

<p><%= link_to('Add new group', new_groups_path	)%> </p>
<p> <%= link_to("Back", :back)%> </p>

app/views/users/index.html.erb
<h3 class = "d-flex justify-content-center align-items-center fs-1 m-4">Welcome</h3>
<div class = "d-flex justify-content-center align-items-center w-100 m-auto ">
<strong class = "w-25">

<%= link_to('My Patients', my_patients_path, class:"fw-bold fs-3 text-secondary text-decoration-none")%>

</strong>
<strong class = "w-25" > <%= link_to('External Patients', patients_path, class:"fw-bold fs-3 text-secondary text-decoration-none")%> </strong>
<strong class = "w-25">

<%= link_to('My Groups', groups_path,class:"fw-bold fs-3 text-decoration-none text-secondary text-primary")%>

</strong>


</div>

app/views/users/patient.html.erb
<div class = "d-flex justify-content-center">

<div class = "mt-2">


<h1 class = "mt-4 fs-4 text-center">All Patients</h1>

<ul> <% if @patients_with_group %> 


<table class = "table table-hover table-responsive caption-top bg-light vw-100">
<caption> <strong> List of patients</strong> </caption>
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Ailment</th>
      <th scope="col">Treatment Cost</th>
    </tr>
  </thead>
  <% @patients_with_group.each_with_index do |patient,index|%>
<tbody>
    <tr>
      <th scope="row"><%= index + 1%></th>
      <td > <%= patient.name %> </p></td>
      
      <td><%= patient.group.name %></td>
      <td> &#8358 <%= patient.amount %></td>
      
    </tr>
<%end%>
<td class = "fw-bold">Total treatment cost </td> <td></td> <td></td> <td class = "fw-bold"> &#8358 <%=  @sum_of_amount%>
</td>
    </tbody>
</table>

<% else %>
<p> No patient without group</p>

<% end%>

<div class = "d-flex justify-content-between mt-4"> <p><%= link_to('Add new patient', new_patient_url, class:"fw-bold btn btn-primary text-decoration-none")%> </p>
<p> <%= link_to('External Patients', patients_path, class:"fw-bold text-decoration-none btn btn-primary")%> </p>
<p> <%= link_to("Back", :back, class:"fw-bold text-decoration-none btn btn-primary")%> </p>
 </div>

app/views/users/show.html.erb
<h1>
Welcome

</h1>

<p>
<% if @patient %> <div>
<%=@patients.each do |patient| %>
<p>
<%= patient.name%>
</p>
  </div>
<% end %>
</p>